# 워크플로우의 이름
name: Android CD 

# pull_request 이벤트가 발생하고, deploy-dev 브랜치에서 생성된 경우 워크플로우가 실행됨
on:
  pull_request:
    branches: [ deploy-dev ] 

jobs:
  deploy:
    # 작업을 실행할 운영체제
    runs-on: ubuntu-latest 

    #step 속성을 통해 작업 순서 정의. 각 작업(job)은 하나 이상의 단계 (step)으로 정의
    # 각 단계 앞에 반드시 - 명시
    #워크플로우가 레포지토리에 접근할 수 있게 checkout
    steps:
      # 워크스페이스를 체크아웃. v3 버전 사용.
      - uses: actions/checkout@v3
        with:
          # 이전 commit 기록들까지 모두 가져오기 위해서 fetch-depth를 0으로 설정.
          fetch-depth: 0

      #안드로이드 프로젝트 빌드를 위한 기본 셋팅
      # JDK 17을 설정.
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
      
      # 안드로이드 SDK 설정.
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
  
      # Gradle 패키지 캐시.
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      # gradlew 파일에 실행 권한 부여.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 비밀 정보를 저장한 secrets.tar.gpg 파일을 복호화.
			# 테스트 환경에서는 해당 파일 없음으로 주석
      #- name: Decrypt secrets.tar.gpg
      #  run: gpg --quiet --batch --yes --always-trust --decrypt --passphrase="$SECRET_GPG_PASSWORD" --output secrets.tar secrets.tar.gpg
      #  env:
      #    # GitHub Secrets에서 비밀 정보를 가져와 사용.
      #    SECRET_GPG_PASSWORD: ${{ secrets.SECRET_GPG_PASSWORD }}

      # secrets.tar 파일을 해제.
      #- name: Unzip secrets.tar
      #  run: tar xvf secrets.tar

      # 릴리스 유니버설 APK 빌드
      - name: Build release universal apk
        run: ./gradlew presentation:packageReleaseUniversalApk

      # Firebase App Distribution에 APK 업로드
      - name: Upload apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }} # Firebase App ID
          token: ${{ secrets.FIREBASE_TOKEN }} # Firebase 토큰
          groups: runnerbe # 배포 대상 그룹
          file: presentation/build/outputs/universal_apk/release/presentation-release-universal.apk # 업로드 할 APK 파일 경로
          releaseNotesFile: documents/release-note/default-note.txt # 릴리스 노트 파일 경로
